version: '3'
services:
  web-api:
    build:
      context: ../../.
      dockerfile: Dockerfile
    container_name: web_api
    env_file:
      - ../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 10000:80